[env]
REBUILD_DAVE_IO_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'
idiomatic_version_file = false
idiomatic_version_file_enable_tools = []

[tools]
bun = { version = '1.2.21' }
node = { version = '22.19.0' }
rust = { version = '1.89.0' }

[tasks]
'claude' = { run = "claude", description = "Invoke Claude Code", alias = "cc" }
