name: ci
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: bun
        uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2
        with:
          bun-version: 1.2.20
      - name: install
        run: bun install
      - name: trunk
        uses: trunk-io/trunk-action@1c401dfb3626be3d242d50537e2f020e12424329
      - name: typecheck
        run: bun run lint:types
      - name: build
        run: bun run build
